### ISSUE TITLE
Xcode 13 build fails - Module '_Builtin_intrinsics.intel' requires feature 'x86'

### ISSUE THREAD

**Issue by ds8k** [ctreffs/SwiftSDL2#11]
### Bug Description

I'm attempting to add this as a dependency to the [sm64ex-ios project](https://github.com/ckosmic/sm64ex-ios) but building with Xcode 13 fails with the following error:

```
module.modulemap:38:19: Module '_Builtin_intrinsics.intel' requires feature 'x86'
```

### Information

- **Package version:** `master` branch
- **Platform version:** macOS 11.6
- **Swift version:**
```
 % swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
Target: x86_64-apple-macosx11.0
```

### Checklist

- [x] If possible, I've reproduced the issue using the `main`/`master` branch of this package.
- [x] I've searched for existing issues under the issues tab.
- [x] The bug is reproducible

### Steps to Reproduce

- Add as a dependency to an existing project in Xcode 13
- Attempt to build

### Expected behavior

Dependency builds successfully

### Actual behavior

Build fails

### Screenshots

![Screen Shot 2021-11-17 at 1 33 05 PM](https://user-images.githubusercontent.com/4458812/142261205-24001eef-7fa3-4ee3-a1f9-6446d80c1cf6.png)

**Comment by pablormago** [comment]
Hi, did you found a solution?? i have the same issue

**Comment by ctreffs** [comment]
I'm sorry but I can't reproduce this issue. Could you provide a demo project demonstrating the issue? 
Are you on an Intel or ARM based mac?

**Comment by pablormago** [comment]
I solved the problem. The problem was the sandbox. Disabling it solved the problem. Naybe you can put and advise on github for future noob issues.

Ps: I couldnt find a way to embed the sdl2 .dylib library, do you know how to do It?? I made a test project so you can see if there is any mistake. It works ok in my Mac but when i give the app to other people it crashes looking for the sdl2_2....dylib file: https://github.com/pablormago/sdlTest

Thanks in advance

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ctreffs** [comment]
I'm afraid I don't have an answer to that, since I faced that issue myself before. https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#requiring-system-libraries does not help either and I couldn't find any information on how to achieve this myself.

**Comment by pablormago** [comment]
Thanks anyway!! I will continue investigating!!El 29 mar. 2022 9:42, Christian Treffs ***@***.***> escribió:
I'm afraid I don't have an answer to that, since I faced that issue myself before. https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#requiring-system-libraries does not help either and I couldn't find any information on how to achieve this myself.
